name: morph_wallet
description: The Best Solana Wallet

version: 0.0.1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
  
  fonts:
    - family: CircularStd
      fonts:
        - asset: assets/fonts/CircularStd-Book.otf
        - asset: assets/fonts/CircularStd-Light.otf
          weight: 300
        - asset: assets/fonts/CircularStd-Medium.otf
          weight: 600
        - asset: assets/fonts/CircularStd-Bold.otf
          weight: 700