name: morph_wallet
description: The Best Solana Wallet
version: 0.0.1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  bip39_mnemonic: ^3.0.5
  cupertino_icons: ^1.0.2
  encrypt: ^5.0.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_dotenv: ^5.0.2
  get_it: ^7.2.0
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  pretty_qr_code: ^2.0.2
  solana: ^0.26.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/fonts/
    - assets/fonts/icons_font/
    - assets/images/

  # Font weight reference: https://fonts.google.com/specimen/Inter?query=Inter
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: MorphIcon
      fonts:
        - asset: assets/fonts/icons_font/icons_font.ttf
